services:
  - type: web
    name: ip-tracking-web
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn core.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: core.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"

  - type: worker
    name: ip-tracking-celery
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: celery -A core worker -l info
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: core.settings
      - key: CELERY_BROKER_URL
        fromService:
          name: redis
          type: redis

fromService:
  name: redis
  type: redis
  property: connectionString